version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: animeconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_only
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata: